/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      boxShadow: {
        default: '0 5px 15px -3px rgba(0, 0, 0, 0.2)',
        'default-inset': 'inset 0 5px 15px -3px rgba(0, 0, 0, 0.2)',
      },
      colors: {
        'tw-primary': {
          DEFAULT: 'var(--color-primary)',
          lighter: {
            1: 'var(--color-primary-lighter-1)',
            2: 'var(--color-primary-lighter-2)',
            3: 'var(--color-primary-lighter-3)',
            4: 'var(--color-primary-lighter-4)',
            5: 'var(--color-primary-lighter-5)',
            6: 'var(--color-primary-lighter-6)',
            7: 'var(--color-primary-lighter-7)',
            8: 'var(--color-primary-lighter-8)',
            9: 'var(--color-primary-lighter-9)',
            10: 'var(--color-primary-lighter-10)',
          },
          darker: {
            1: 'var(--color-primary-darker-1)',
            2: 'var(--color-primary-darker-2)',
            3: 'var(--color-primary-darker-3)',
            4: 'var(--color-primary-darker-4)',
            5: 'var(--color-primary-darker-5)',
            6: 'var(--color-primary-darker-6)',
            7: 'var(--color-primary-darker-7)',
            8: 'var(--color-primary-darker-8)',
            9: 'var(--color-primary-darker-9)',
            10: 'var(--color-primary-darker-10)',
          },
          contrast: 'var(--color-primary-contrast)',
          text: 'var(--color-primary-text)',
        },
        bg: {
          DEFAULT: 'var(--color-bg-primary)',
          lighter: {
            1: 'var(--color-bg-primary-lighter-1)',
            2: 'var(--color-bg-primary-lighter-2)',
            3: 'var(--color-bg-primary-lighter-3)',
            4: 'var(--color-bg-primary-lighter-4)',
            5: 'var(--color-bg-primary-lighter-5)',
            6: 'var(--color-bg-primary-lighter-6)',
            7: 'var(--color-bg-primary-lighter-7)',
            8: 'var(--color-bg-primary-lighter-8)',
            9: 'var(--color-bg-primary-lighter-9)',
            10: 'var(--color-bg-primary-lighter-10)',
          },
          darker: {
            1: 'var(--color-bg-primary-darker-1)',
            2: 'var(--color-bg-primary-darker-2)',
            3: 'var(--color-bg-primary-darker-3)',
            4: 'var(--color-bg-primary-darker-4)',
            5: 'var(--color-bg-primary-darker-5)',
            6: 'var(--color-bg-primary-darker-6)',
            7: 'var(--color-bg-primary-darker-7)',
            8: 'var(--color-bg-primary-darker-8)',
            9: 'var(--color-bg-primary-darker-9)',
            10: 'var(--color-bg-primary-darker-10)',
          },
        },
        'tw-secondary': {
          DEFAULT: 'var(--color-secondary)',
          lighter: {
            1: 'var(--color-secondary-lighter-1)',
            2: 'var(--color-secondary-lighter-2)',
            3: 'var(--color-secondary-lighter-3)',
            4: 'var(--color-secondary-lighter-4)',
            5: 'var(--color-secondary-lighter-5)',
            6: 'var(--color-secondary-lighter-6)',
            7: 'var(--color-secondary-lighter-7)',
            8: 'var(--color-secondary-lighter-8)',
            9: 'var(--color-secondary-lighter-9)',
            10: 'var(--color-secondary-lighter-10)',
          },
          darker: {
            1: 'var(--color-secondary-darker-1)',
            2: 'var(--color-secondary-darker-2)',
            3: 'var(--color-secondary-darker-3)',
            4: 'var(--color-secondary-darker-4)',
            5: 'var(--color-secondary-darker-5)',
            6: 'var(--color-secondary-darker-6)',
            7: 'var(--color-secondary-darker-7)',
            8: 'var(--color-secondary-darker-8)',
            9: 'var(--color-secondary-darker-9)',
            10: 'var(--color-secondary-darker-10)',
          },
          emphasis: 'var(--color-secondary-emphasis)',
        },
        buttons: {
          DEFAULT: 'var(--color-btn-primary)',
          text: 'var(--color-btn-primary-text)',
          hover: 'var(--color-btn-primary-hover)',
        },
        inputs: {
          emphasis: 'var(--color-inputs-emphasis)',
        },
        'gray-coco': 'var(--color-gray-coco)',
      },
      screens: {
        'mobile-min': '576px',
        'mobile-max': { max: '575px' },
        'tablet-min': '768px',
        'tablet-max': { max: '767px' },
        'desktop-min': '992px',
        'desktop-max': { max: '991px' },
      },
      fontFamily: {
        titles: ['Asap', 'sans-serif'],
        body: ['Open Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
